Repository LimeChain/hedera-services, pull requests merged in 2020-09, with the labels that each got.

#32 Feat/token Protobuf Updates
  hapi-fees/src/main/java/com/hedera/services/usage/token/TokenCreateUsage.java
  hapi-fees/src/test/java/com/hedera/services/usage/token/TokenCreateUsageTest.java
  hapi-fees/src/test/java/com/hedera/services/usage/token/TokenUsageUtilsTest.java
  hapi-proto/HAPI.html
  hapi-proto/README.md
  hapi-proto/src/main/proto/BasicTypes.proto
  hapi-proto/src/main/proto/CryptoGetAccountBalance.proto
  hapi-proto/src/main/proto/ResponseCode.proto
  hapi-proto/src/main/proto/TokenCreate.proto
  hapi-proto/src/main/proto/TokenGetInfo.proto
  hapi-proto/src/main/proto/TokenManagement.proto
  hapi-proto/src/main/proto/TokenService.proto
  hapi-proto/src/main/proto/TransactionBody.proto
  hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/src/main/java/com/hedera/services/queries/crypto/GetAccountInfoAnswer.java
  hedera-node/src/main/java/com/hedera/services/sigs/order/HederaSigningOrder.java
  hedera-node/src/main/java/com/hedera/services/tokens/ExceptionalTokenStore.java
  hedera-node/src/main/java/com/hedera/services/tokens/HederaTokenStore.java
  hedera-node/src/main/java/com/hedera/services/tokens/TokenStore.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenCreateTransitionLogic.java
  hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerTest.java
  hedera-node/src/test/java/com/hedera/services/tokens/HederaTokenStoreTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenCreateTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  hedera-node/src/test/java/com/hedera/test/factories/txns/TokenCreateFactory.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnFactory.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenDelete.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
Labels: documentation, enhancement

#31 Tests: BDD Tests for Token name and Token wipe
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Labels: enhancement

#35 Docs/protobuf token update
  hapi-proto/HAPI.html
  hapi-proto/src/main/proto/TokenManagement.proto
  hapi-proto/src/main/proto/TokenUpdate.proto
  hapi-proto/src/main/proto/TransactionBody.proto
  hedera-node/src/main/java/com/hedera/services/sigs/order/HederaSigningOrder.java
  hedera-node/src/main/java/com/hedera/services/tokens/ExceptionalTokenStore.java
  hedera-node/src/main/java/com/hedera/services/tokens/HederaTokenStore.java
  hedera-node/src/main/java/com/hedera/services/tokens/TokenStore.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenUpdateTransitionLogic.java
  hedera-node/src/test/java/com/hedera/services/tokens/HederaTokenStoreTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenUpdateTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  hedera-node/src/test/java/com/hedera/test/factories/txns/TokenUpdateFactory.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnFactory.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
Labels: documentation

#39 Fix(token): burn must not decrement total supply if adjustments fail
  hedera-node/src/main/java/com/hedera/services/tokens/HederaTokenStore.java
  hedera-node/src/test/java/com/hedera/services/tokens/HederaTokenStoreTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
Labels: bug

#40 Fix(token): Deleting an already deleted token must return an error
  hedera-node/src/main/java/com/hedera/services/tokens/TokenStore.java
  hedera-node/src/test/java/com/hedera/services/tokens/HederaTokenStoreTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenDeleteTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java
Labels: bug

#52 Docs: Add Token Transfer documentation
  hapi-fees/src/test/java/com/hedera/services/usage/token/TokenTransactUsageTest.java
  hapi-proto/HAPI.html
  hapi-proto/src/main/proto/BasicTypes.proto
  hapi-proto/src/main/proto/ConsensusCreateTopic.proto
  hapi-proto/src/main/proto/CryptoTransfer.proto
  hapi-proto/src/main/proto/ResponseCode.proto
  hapi-proto/src/main/proto/TokenBurn.proto
  hapi-proto/src/main/proto/TokenCreate.proto
  hapi-proto/src/main/proto/TokenFreezeAccount.proto
  hapi-proto/src/main/proto/TokenGetInfo.proto
  hapi-proto/src/main/proto/TokenMint.proto
  hapi-proto/src/main/proto/TokenTransact.proto
  hapi-proto/src/main/proto/TokenTransfer.proto
  hapi-proto/src/main/proto/TokenUpdate.proto
  hapi-proto/src/main/proto/TokenWipeAccount.proto
  hapi-proto/src/main/proto/TransactionBody.proto
  hapi-proto/src/main/proto/TransactionRecord.proto
  hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
  hedera-node/src/main/java/com/hedera/services/ledger/HederaLedger.java
  hedera-node/src/main/java/com/hedera/services/sigs/order/HederaSigningOrder.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenTransferTransitionLogic.java
  hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenTransferTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  hedera-node/src/test/java/com/hedera/test/factories/txns/TokenTransactFactory.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnFactory.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenTransact.java
Labels: documentation

#55 Docs(token): add error clarification on freeze/unfreeze/grantKYC/revokeKYC/wipe
  hapi-proto/HAPI.html
  hapi-proto/src/main/proto/TokenFreezeAccount.proto
  hapi-proto/src/main/proto/TokenGrantKyc.proto
  hapi-proto/src/main/proto/TokenRevokeKyc.proto
  hapi-proto/src/main/proto/TokenUnfreezeAccount.proto
  hapi-proto/src/main/proto/TokenWipeAccount.proto
Labels: documentation

#58 Docs(token): Add associate/dissociate information
  hapi-proto/HAPI.html
  hapi-proto/src/main/proto/TokenAssociate.proto
  hapi-proto/src/main/proto/TokenDissociate.proto
Labels: documentation

#66 Feature(token): Prechecks on Token Operations
  hapi-proto/HAPI.html
  hapi-proto/src/main/proto/ResponseCode.proto
  hedera-node/configuration/compose/application.properties
  hedera-node/configuration/dev/application.properties
  hedera-node/configuration/nextRelease/application.properties
  hedera-node/src/main/java/com/hedera/services/context/ServicesContext.java
  hedera-node/src/main/java/com/hedera/services/context/properties/StandardizedPropertySources.java
  hedera-node/src/main/java/com/hedera/services/legacy/config/PropertiesLoader.java
  hedera-node/src/main/java/com/hedera/services/legacy/config/SyncPropertiesObject.java
  hedera-node/src/main/java/com/hedera/services/legacy/logic/ApplicationConstants.java
  hedera-node/src/main/java/com/hedera/services/tokens/HederaTokenStore.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenAssociateTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenBurnTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenCreateTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenDeleteTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenDissociateTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenFreezeTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenGrantKycTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenMintTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenRevokeKycTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenTransferTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenUnfreezeTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenUpdateTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenWipeTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/validation/ContextOptionValidator.java
  hedera-node/src/main/java/com/hedera/services/txns/validation/OptionValidator.java
  hedera-node/src/main/java/com/hedera/services/txns/validation/TokenListChecks.java
  hedera-node/src/test/java/com/hedera/services/context/properties/StandardizedPropertySourcesTest.java
  hedera-node/src/test/java/com/hedera/services/tokens/HederaTokenStoreTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenAssociateTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenBurnTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenCreateTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenDeleteTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenDissociateTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenFreezeTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenGrantKycTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenMintTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenRevokeKycTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenTransferTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenUnfreezeTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenUpdateTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenWipeTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/validation/ContextOptionValidatorTest.java
  hedera-node/src/test/java/com/hedera/test/mocks/TestContextValidator.java
  hedera-node/src/test/java/com/hedera/test/utils/TxnUtils.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Labels: enhancement

#69 Fix(token): Restrict empty token transfers
  hapi-proto/HAPI.html
  hapi-proto/src/main/proto/ResponseCode.proto
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenTransferTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/validation/ContextOptionValidator.java
  hedera-node/src/main/java/com/hedera/services/txns/validation/OptionValidator.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenTransferTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/validation/ContextOptionValidatorTest.java
  hedera-node/src/test/java/com/hedera/test/mocks/TestContextValidator.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenTransact.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
Labels: bug, enhancement
